# Generated by Django 4.1.3 on 2022-11-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_tech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nascimento',
            new_name='data_nascimento',
        ),
    ]
